---
deployment:
  tasks:
    - export DEPLOYPATH=/home/paxdv334fokc/public_html/
    - rm -R $DEPLOYPATH/images
    - rm -R $DEPLOYPATH/images_mini
    - rm -R $DEPLOYPATH/oimages
    - rm -R $DEPLOYPATH/index.html
    - cp -R $DEPLOYPATH/images
    - cp -R $DEPLOYPATH/images_mini
    - cp -R $DEPLOYPATH/oimages
    - cp -R $DEPLOYPATH/index.html
