---
deployment:
  tasks:
    - export DEPLOYPATH=/home/paxdv334fokc/public_html/
    - rm -R $DEPLOYPATH/images
    - rm -R $DEPLOYPATH/images_mini
    - rm -R $DEPLOYPATH/oimages
    - rm $DEPLOYPATH/index.html
    - /bin/cp -R ./images $DEPLOYPATH/images
    - /bin/cp -R ./images_mini $DEPLOYPATH/images_mini
    - /bin/cp -R ./oimages $DEPLOYPATH/oimages
    - /bin/cp ./index.html $DEPLOYPATH/index.html
