---
deployment:
  tasks:
    - export DEPLOYPATH=/home/paxdv334fokc/public_html/
    - rm -R $DEPLOYPATH/images
    - rm -R $DEPLOYPATH/images_mini
    - rm -R $DEPLOYPATH/oimages
    - rm $DEPLOYPATH/index.html
    - /bin/cp -R $DEPLOYPATH/images
    - /bin/cp -R $DEPLOYPATH/images_mini
    - /bin/cp -R $DEPLOYPATH/oimages
    - /bin/cp $DEPLOYPATH/index.html
